name: React App Github pages deploy

on:
  push:
    branch:
      "master"
jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      name: Checkout
      uses: actions/checkout@v3

      name: Install & build
      run: npm i && npm run build

      name: Deploy
      uses: actions/deploy-pages/@v4